#!/bin/bash

# ./rolling-files --source-path a --dest-path b --auto-yes c

# ----- handle arguments ---- >

while [ $# -ne 0 ]
do
    arg="$1"
    case "$arg" in
        --source-path)
            SOURCE_PATH=$2
            ;;
        --dest-path)
            DEST_PATH=$2
            ;;
        --auto-yes)
            AUTO_YES=$2
            ;;
       *)
            ;;
    esac
    shift
done

# ----------- main --------------- >

AUTO_YES=${AUTO_YES:-false}

if [ -z $SOURCE_PATH ]; then
 echo "source path is required."
 exit 1
fi

if [ -z $DEST_PATH ]; then
 echo "dest path is required."
 exit 1
fi

echo "AUTO YES? ${AUTO_YES}"
echo "SOURCE PATH: ${SOURCE_PATH}"
echo "DEST PATH: ${DEST_PATH}"

FILE_LIST=$(ls -lrth  $SOURCE_PATH | grep -E "([a-zA-Z0-9_]+)_[[:digit:]]{8}_[[:digit:]]{6}\.(bz2|tar\.gz)" | awk {'print $9'} | sed -E 's/\.part-[0-9]+$//' | uniq | sort)

if [ $(echo "$FILE_LIST" | wc -l) -le 1 ]; then
 echo "not thing to do."
else
 FILES_TO_MOVE=$(echo "$FILE_LIST" | head -n -1)
 FILES_TO_KEEP=$(echo "$FILE_LIST" | tail -n 1) 
 
 echo "FILES TO MOVE:" 
 echo "$FILES_TO_MOVE" | xargs -n 1 echo -e "\t"
 echo "FILES TO KEEP:"
 echo "$FILES_TO_KEEP" | xargs -n 1 echo -e "\t"

 read -rp "Are you sure you want to continue? [Y/n] " key 

 if [ "$key" = 'Y' ] || [ "$key" = 'y' ]; then
  echo "Y."
  RAND_NAME=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 6 | head -n 1)
  ls -l $SOURCE_PATH | awk '{ print $9 }' > /tmp/source_files_$RAND_NAME
  echo "$FILES_TO_MOVE" | xargs -I {} grep -n {} /tmp/source_files_$RAND_NAME | sed 's/^\([0-9]\{1,\}\:\)//g' | xargs -n 1 -i echo "$SOURCE_PATH/{}" | xargs -n 1 -i rsync -avh --progress --remove-source-files {} $DEST_PATH
 else
  echo "Abort."
 fi

fi
